{{- if .Values.kubeRBACProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default-scheduler-controller.fullname" . }}-metrics-service
  labels:
    {{- include "default-scheduler-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "default-scheduler-controller.selectorLabels" . | nindent 4 }}
{{- end }}
